- name: Docker | Install packages that allow apt to be used over HTTPS
  apt:
    state: present
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Docker | Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker | Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Docker | Install docker and its dependencies
  apt:
    state: present
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
