version: "3.8"
services:
  nvim:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
    container_name: ubuntu-dotfiles
    image: koenverburg/dotfiles/ubuntu-docker
    volumes:
      - .:/usr/src/
