- defaults:
    link:
      relink: true

- clean: ['~']

- create:
    - ~/.config/alacritty
    - ~/.config/yabai
    - ~/.config/limelight
    - ~/.config/skhd
    - ~/.config/starship/themes
    - ~/.config/zellij
    # - ~/.hammerspoon

- link:
    # ~/.config/nvim: .config/nvim
    ~/.tmux.conf: ansible/playbooks/roles/tmux/files/.tmux.conf
    ~/.config/nvim: ~/code/github/nvim
    ~/.zshrc: .config/zsh/.zshrc
    ~/.config/alacritty/alacritty.yml: .config/alacritty/alacritty.macos.yml
    ~/.gitconfig: .config/gitconfig/.gitconfig

    ~/.config/starship.toml: .config/starship/starship.toml
    ~/.config/starship/themes/default.toml: .config/starship/starship.toml
    ~/.config/starship/themes/cyberpunk.toml: .config/starship/themes/cyberpunk.toml
    ~/.config/starship/themes/minimal.toml: .config/starship/themes/minimal.toml
    ~/.config/starship/themes/slanted.toml: .config/starship/themes/slanted.toml

    ~/.config/zellij/config.kdl: .config/zellij/config.kdl
    ~/.config/zellij/layouts: .config/zellij/layouts
    # ~/.config/yabai/yabairc: .config/yabai/yabairc
    # ~/.config/limelight/limelightrc: .config/limelight/limelightrc
    # ~/.config/skhd/skhdrc: .config/skhd/skhdrc
    # ~/.hammerspoon/init.lua: .config/hammerspoon/init.lua

    "~/Library/Application Support/lazygit/config.yml": .config/lazygit/config.yml
    "~/Library/Application Support/nushell/config.nu": .config/nushell/config.nu
    "~/Library/Application Support/nushell/black-metal-bathory.nu": .config/nushell/black-metal-bathory.nu

- shell:

    mkdir -p ~/.config/zellij/plugins && curl -L "https://github.com/rvcas/room/releases/latest/download/room.wasm" -o ~/.config/zellij/plugins/room.wasm
    mkdir -p ~/.config/zellij/plugins && curl -L "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm" -o ~/.config/zellij/plugins/zjstatus.wasm

    # - [git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions]
    # - [curl -sS https://starship.rs/install.sh | sh]
    # - [curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash]
    # - [git submodule update --init --recursive, Installing submodules]
    # - [git clone https://github.com/AdamWagner/stackline.git ~/.hammerspoon/stackline]
    # - [brew tap homebrew/cask-fonts]
    # - [brew install cask font-hack-nerd-font]
    # - [brew install neovim --head]
    # - [brew install lua fzf bat delta ninja libtool automake cmake pkg-config gettext] # neovim development
    # - [brew install node yarn]
