- defaults:
    link:
      relink: true

- clean: ["~"]

- link:
    ~/AppData/local/nvim: .config/nvim
    ~/AppData/Roaming/alacritty/alacritty.yml: .config/alacritty/alacritty.win.yml
    ~/AppData/Roaming/Code/User/settings.json: .config/vscode/settings.json
    ~/AppData/Roaming/Code/User/keybindings.json: .config/vscode/keybindings.json
    ~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1: .config/powershell/profile.ps1
    ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1: .config/powershell/profile.ps1

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [./bootstrap.ps1 programs]
