- clean: ["~"]

# - create:
#     - ~/code/tools

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.gitconfig: .config/gitconfig/.gitconfig
    ~/.tmux.conf: ./ansible/playbooks/roles/tmux/files/.tmux.conf
    ~/.config/nvim: ./.config/nvim

- shell:
    - [git submodule update --init --recursive, Installing submodules]

    # Tools
    - sudo apt-get install -y tmux
    - sudo apt-get install -y bat

    # Neovim stuff
    - sudo apt-get install ninja-build gettext libtool-bin cmake g++ pkg-config unzip curl
    - sudo apt-get install -y git
    - sudo apt-get install -y make
    - sudo apt-get install -y gcc
    - sudo apt-get install -y ruby

    # Languages I write in
    # - sudo apt-get install -y python3
    # - sudo apt-get install -y nodejs
    # - sudo apt-get install -y golang

    # Automation tooling
    # - sudo apt-get install -y terraform
    # - sudo apt-get install -y ansible
    - apt-get install -y yq
    - apt-get install -y ripgrep

    - bash ./nvim-appimage.sh

    # Other tooling
    # - cargo install git-delta
    # - nvm install 14.15.4
