-- require("shade").setup {
--   opacity_step = 10,
--   overlay_opacity = 25,
--
--   keys = {
--     toggle = "<Leader>s",
--     brightness_up = "<C-Up>",
--     brightness_down = "<C-Down>",
--   }
-- }
