- name: Check if .config is already exists
  register: config_local
  stat:
    path: "~/.config"

- name: Check if .config is already exists
  when: not config_local.stat.exists
  shell: mkdir ~/.config

- name: Check if .config/nvim is already exists
  register: n_config_local
  stat:
    path: "~/.config/nvim"

- name: Check if .config/nvim is already exists
  when: not n_config_local.stat.exists
  shell: mkdir ~/.config/nvim

- name: Check if Neovim is already cloned
  register: neovim_local
  stat:
    path: "~/neovim"

- name: Clone Neovim repository
  when: not neovim_local.stat.exists
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "~/neovim"
    clone: yes

- name: Make | clean dist folder
  when: not neovim_local.stat.exists
  shell: |
    cd ~/neovim
    sudo make distclean

- name: Make | build release
  when: not neovim_local.stat.exists
  shell: |
    cd ~/neovim
    sudo make CMAKE_BUILD_TYPE=Release

- name: Make | Install
  when: not neovim_local.stat.exists
  shell: |
    cd ~/neovim
    sudo make install

# - name: Symlink Nvim config
#   become_user: conrad
#   file:
#     src: "{{ lookup('env', 'ROOTDIR') }}/.config/nvim"
#     dest: ~/.config/nvim
#     state: link
