- name: Check if there is a local copy of neovim 
  tags:
    - neovim
  register: neovim_local
  stat:
    path: "~/code/tools/neovim"

- name: Git | Pull latest changes if local copy exists
  when: neovim_local.stat.exists
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: ~/code/tools/neovim
    update: yes
  tags:
    - neovim

- name: Git | Clone Neovim repository
  when: not neovim_local.stat.exists
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "~/code/tools/neovim"
    clone: yes
  tags:
    - neovim

- name: Make | build release
  tags:
    - neovim
  # when: not neovim_local.stat.exists
  shell: |
    cd ~/codetools/neovim
    sudo make CMAKE_BUILD_TYPE=RelWithDebInfo

- name: Make | Install
  tags:
    - neovim
  # when: not neovim_local.stat.exists
  shell: |
    cd ~/code/tools/neovim
    sudo make install

