git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: "C"
    command: "committer"
    context: "files"
    loadingText: "opening my commit tool"
    subprocess: true

gui:
  showCommandLog: false
