- name: Check if there is a local copy of neovim 
  tags:
    - neovim
  register: neovim_local
  stat:
    path: "~/tools/neovim"

- name: Git | Pull latest changes if local copy exists
  when: neovim_local.stat.exists
  tags:
    - neovim
  shell: |
    cd ~/tools/neovim
    git pull

- name: Git | Clone Neovim repository
  when: not neovim_local.stat.exists
  tags:
    - neovim
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "~/tools/neovim"
    clone: yes

- name: Brew | install all deps for neovim
  tags:
    - neovim
  shell: |
    brew install ninja libtool automake cmake pkg-config gettext curl

- name: Make | build release
  tags:
    - neovim
  # when: not neovim_local.stat.exists
  shell: |
    cd ~/tools/neovim
    sudo make CMAKE_BUILD_TYPE=RelWithDebInfo

- name: Make | Install
  tags:
    - neovim
  # when: not neovim_local.stat.exists
  shell: |
    cd ~/tools/neovim
    sudo make install

