format = """
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""
# $cmd_duration\
# $kubernetes\

right_format = """
$nodejs\
$lua\
$go\
$rust\
$helm\
"""


[directory]
style = "blue"

[character]
success_symbol = "[#](purple)"
error_symbol = "[#](red)"
vimcmd_symbol = "[#](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = '%T'
# time_range = '10:00:00-14:00:00'

[nodejs]
format = ' [$version](bold green) '

[helm]
format = '[⎈ $version](bold white) '

[kubernetes]
disabled = false
symbol = "⎈ "
format = "[$symbol$context@$namespace](yellow)"
detect_folders = ['k8s']

[kubernetes.context_aliases]
'do-ams3-k8s-do-ams-3-pool-01' = 'digitalocean-p01'
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\\w-]+)' = 'gke-$var_cluster'

[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'
