name: Regression Pipeline

on: push

jobs:
  # nixos - Jupiter

  # Mars
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          tag-sha: true
          images: |
            ghcr.io/koenverburg/dotfiles/mars-ubuntu

      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          targets: mars
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}

  # Saturnus
  # Windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.7.0
  #       with:
  #         access_token: ${{ github.token }}

  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - name: Setup
  #       run: ./install.ps1

  # Atlas
  macos:
    runs-on: macos-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup
        run: sudo bash ./macos.install
