name: Regression Pipeline

on: push

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          tag-sha: true
          images: |
            ghcr.io/koenverburg/dotfiles/ra-ubuntu

      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          targets: ra
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
      # - name: Install Dependencies
      #   run: | 
      #     sudo apt-get update
      #     sudo apt-get install -y --no-install-recommends
      #     sudo apt-get install g++
      #     sudo apt-get install sudo
      #     sudo apt-get install gcc
      #     sudo apt-get install apt-utils
      #     sudo apt-get install libc6-dev
      #     sudo apt-get install make
      #     sudo apt-get install git
      #     sudo apt-get install python3-apt
      #     sudo apt-get install python3.8
      #     sudo apt-get install ansible

      - name: Setup
        run: |
          # sudo rm ~/.config/fish/config.fish
          sudo bash ./install

  # Windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.7.0
  #       with:
  #         access_token: ${{ github.token }}

  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - name: Setup
  #       run: ./install.ps1

  # Macos:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.7.0
  #       with:
  #         access_token: ${{ github.token }}

  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - name: Setup
  #       run: sudo bash ./macos.install
